import Link from 'next/link';
import { BarChart3 } from 'lucide-react';

export function Footer() {
  return (
    <footer className="border-t border-white/[0.06] bg-surface mt-auto">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-10">
        <div className="grid grid-cols-1 md:grid-cols-4 gap-8">
          {/* Brand */}
          <div className="md:col-span-2">
            <div className="flex items-center gap-2.5 mb-3">
              <div className="w-7 h-7 bg-gradient-to-br from-accent to-violet-400 rounded-lg flex items-center justify-center">
                <BarChart3 className="w-3.5 h-3.5 text-white" />
              </div>
              <span className="font-display text-base font-bold text-white">BizzBuy</span>
            </div>
            <p className="text-sm text-t-secondary leading-relaxed max-w-sm">
              AI-powered acquisition diligence for non-expert buyers. Know affordability, risk, and transferability before you sign.
            </p>
          </div>

          {/* Links */}
          <div>
            <p className="text-xs font-semibold text-t-muted uppercase tracking-wider mb-3">Product</p>
            <div className="space-y-2">
              <Link href="/analyze/upload" className="block text-sm text-t-secondary hover:text-white transition-colors">
                Analyze a Business
              </Link>
              <Link href="/pricing" className="block text-sm text-t-secondary hover:text-white transition-colors">
                Pricing
              </Link>
              <Link href="/analyze/upload?demo=true" className="block text-sm text-t-secondary hover:text-white transition-colors">
                Try Demo
              </Link>
            </div>
          </div>

          <div>
            <p className="text-xs font-semibold text-t-muted uppercase tracking-wider mb-3">Company</p>
            <div className="space-y-2">
              <Link href="/team" className="block text-sm text-t-secondary hover:text-white transition-colors">
                Meet the Team
              </Link>
            </div>
          </div>
        </div>

        <div className="mt-10 pt-6 border-t border-white/[0.06] flex flex-col sm:flex-row items-center justify-between gap-4">
          <p className="text-xs text-t-muted">
            &copy; {new Date().getFullYear()} BizzBuy. All rights reserved.
          </p>
          <p className="text-xs text-t-muted text-center max-w-lg">
            This analysis is generated by AI for informational purposes only. It does not constitute financial, legal, or investment advice.
          </p>
        </div>
      </div>
    </footer>
  );
}
