import { BarChart3 } from 'lucide-react';

export function Footer() {
  return (
    <footer className="border-t border-slate-200 bg-white mt-auto">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
        <div className="flex flex-col sm:flex-row items-center justify-between gap-4">
          <div className="flex items-center gap-2 text-slate-600 text-sm font-medium">
            <div className="w-6 h-6 bg-blue-600 rounded flex items-center justify-center">
              <BarChart3 className="w-3 h-3 text-white" />
            </div>
            BizBuy — AI Acquisition Diligence
          </div>
          <p className="text-xs text-slate-400 text-center max-w-lg">
            This analysis is generated by AI for informational purposes only. It does not constitute financial, legal, or investment advice. Consult qualified professionals before making any acquisition decision.
          </p>
        </div>
      </div>
    </footer>
  );
}
